name: Docker Image CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Set short sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portfolio:${{ steps.vars.outputs.sha_short }}
      -
        name: Update Kubernetes resources
        env:
          DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
          NEW_VERSION: '${{ secrets.DOCKER_USERNAME }}\/portfolio:${{ steps.vars.outputs.sha_short }}'
        run: |
          cd aws
          sed -i 's/'$DOCKER_USERNAME'.*/'$NEW_VERSION'/g' dev.yml
      -
        name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump docker tag"
      -
        name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.LOGIN_TOKEN }}
